# Generated by Django 3.1.7 on 2021-04-07 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_master_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_master',
            name='cdate',
            field=models.DateField(default=datetime.datetime.utcnow, verbose_name='Creation Date'),
        ),
    ]
